<strategy> ::= "All Operators" <defaultOperation>

<defaultOperation> ::= <operatorOperation> <defaultOperation> | <mutantOperation> <defaultOperation> | "New Branch" <defaultOperation> <defaultOperation> | "Store Mutants"

<selectionType> ::= "Sequential" | "Random" | "LastToFirst"

<sortingDirection> ::= "Ascending" | "Descending"

<quantity> ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10"

<percentage> ::= "0.1" | "0.2" | "0.3" | "0.4" | "0.5" | "0.6" | "0.7" | "0.8" | "0.9" | "1.0"

## Operações de Operadores

<operatorOperation> ::= "Select Operators" <selectOperators> | "Discard Operators" <selectOperators> | "Execute Operators" <selectOperators> <typeOfOperatorExecution> | "Group Operators" <operatorAttribute>

<selectOperators> ::= <operatorSelectionType> <quantity> | <operatorSelectionType> <percentage>

<operatorSelectionType> ::= "Select Operators" <selectionType> <operatorsSorting> | "Select Operators by Groups" <selectOperatorGroups> <selectionType> <operatorsSorting>

<operatorsSorting> ::=  <operatorAttribute> <sortingDirection> | ""

<selectOperatorGroups> ::= <typeOfOperatorGroupSelection> <quantity> | <typeOfOperatorGroupSelection> <percentage>

<typeOfOperatorGroupSelection> ::= <selectionType> <operatorGroupSorting>

<operatorGroupSorting> ::= "Quantidade Mutantes no Grupo" <sortingDirection> | "Quantidade Operadores no Grupo" <sortingDirection> | ""

<typeOfOperatorExecution> ::= "Conventional Execution"

<operatorAttribute> ::= "Type" | "Mutant Quantity"

## Operações de Mutantes

<mutantOperation> ::= <selectMutants> | <discardMutants> | <combineMutants> | <groupMutants>

<selectMutants> ::= <tipoSelecaoMutantes> <quantity> | <tipoSelecaoMutantes> <percentage>

<tipoSelecaoMutantes> ::= <selectionType> <ordenacaoMutantes> | <selecionarGruposMutantes> <selectionType> <ordenacaoMutantes>

<ordenacaoMutantes> ::= "Ordem" <sortingDirection> | ""

<selecionarGruposMutantes> ::= <tipoSelecaoGruposMutantes> <quantity> | <tipoSelecaoGruposMutantes> <percentage>

<tipoSelecaoGruposMutantes> ::= <selectionType> <ordenacaoGruposMutantes>

<ordenacaoGruposMutantes> ::= "Quantidade Mutantes no Grupo" <sortingDirection> | ""

<descartarMutantes> ::= <selecionarMutantes> "Descartar Mutantes"

<combinarMutantes> ::= <selecionarMutantes> <gerarHOM>

<gerarHOM> ::= "Um HOM" | "Todas as Combinações de HOMs" <ordem> | "Geração Convencional" <ordem>

<ordem> ::= "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10"

<agruparMutantes> ::= "Tipo Operador" | "Operador" | "FOM e HOM" | "Ordem"
